STYLE_PRESET = {'id': 'axe_bahian_carnival_pop',
 'description': {'pt': 'Axe baiano de carnaval com percussao afro-brasileira, respostas de publico, metais ou guitarras brilhantes e energia de trio eletrico para clima festivo ao ar livre.',
                 'en': 'Bahian carnival axe with Afro-Brazilian percussion, crowd-response hooks, bright horns or guitars, and trio eletrico energy for a festive outdoor feel.'},
 'style_family': 'Bahian axe carnival pop',
 'style_prompt': 'Bahian axe and carnival pop with Afro-Brazilian percussion, surdo and timbau '
                 'drive, trio eletrico band projection, bright guitar or horn hooks, powerful lead '
                 'vocal, crowd response, and celebratory outdoor energy.',
 'default_language': 'pt-BR',
 'default_vocal': {'description': 'powerful lead vocal with crowd-response backing vocals'},
 'tempo_bpm': 126,
 'key_scale': 'A major',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['surdo',
                     'timbau',
                     'repique',
                     'bass',
                     'electric guitar',
                     'horns',
                     'keyboards',
                     'drum kit'],
 'arrangement': ['percussion break intro',
                 'lead vocal call',
                 'crowd-response hook',
                 'horn or guitar riff',
                 'extended final chorus'],
 'energy': 'high',
 'mood': ['carnival', 'bright', 'participatory', 'Afro-Bahian', 'celebratory'],
 'mix_target': 'outdoor carnival projection with bright percussion and wide backing vocals',
 'negative_traits': ['small-room intimacy',
                     'weak chorus',
                     'no percussion breaks',
                     'dark minimal club mood',
                     'static arrangement']}


