STYLE_PRESET = {'id': 'blues',
 'description': {'pt': 'Blues americano com groove shuffle ou lento, dialogo entre voz e guitarra, notas dobradas, harmonica ou piano e uma atmosfera intima e resiliente.',
                 'en': 'American blues with a shuffle or slow groove, dialogue between voice and guitar, bent notes, harmonica or piano, and an intimate resilient atmosphere.'},
 'style_family': 'American blues',
 'style_prompt': 'American blues with shuffle, slow 12/8, boogie, or straight pocket feel, guitar '
                 'and vocal dialogue, bent notes, harmonica or piano color, and resilient '
                 'intimacy.',
 'default_language': 'en-US',
 'default_vocal': {'description': 'expressive lead vocal with rasp, moan, bent pitch, and elastic '
                                  'timing'},
 'tempo_bpm': 88,
 'key_scale': 'E blues',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['acoustic or electric guitar',
                     'slide guitar',
                     'harmonica',
                     'piano',
                     'bass',
                     'shuffle drums',
                     'horns'],
 'arrangement': ['12-bar form',
                 'AAB lyric logic',
                 'call-and-response fills',
                 'solo space',
                 'turnaround ending'],
 'energy': 'medium',
 'mood': ['weary', 'smoky', 'defiant', 'intimate'],
 'mix_target': 'vocal and guitar dialogue forward, warm amp tone, roomy drums, and strong pocket',
 'negative_traits': ['over-quantized pop grid',
                     'glossy synth lead',
                     'excessive chord changes',
                     'crowded solos',
                     'thin guitar tone']}


