STYLE_PRESET = {'id': 'brazilian_funk',
 'description': {'pt': 'Funk de baile brasileiro com tamborzao, 808 pesado, loops curtos, sintetizadores de mandelao, canto de MC e pressao crua de pista.',
                 'en': 'Brazilian baile funk with tamborzao drums, heavy 808s, short loops, mandelao synths, MC chants, and raw dance-floor pressure.'},
 'style_family': 'Brazilian baile funk',
 'style_prompt': 'Brazilian baile funk with tamborzao drums, heavy 808 kick, clipped percussion, '
                 'mandelao synth ostinato, volt mix pressure, MC chant delivery, shouted hooks, '
                 'and raw dance-floor pressure.',
 'default_language': 'pt-BR',
 'default_vocal': {'description': 'MC chant vocal with shouted hooks, ad-libs, and callouts'},
 'tempo_bpm': 150,
 'key_scale': 'A minor',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['tamborzao drums',
                     '808 kick',
                     'claps',
                     'sub-bass',
                     'mandelao synth ostinato',
                     'vocal cuts',
                     'sirens'],
 'arrangement': ['producer tag intro',
                 'beat drop',
                 'MC hook',
                 'repeated dance command',
                 'breakdown and return'],
 'energy': 'high',
 'mood': ['raw', 'urban', 'aggressive', 'playful', 'physical'],
 'mix_target': 'loud bass, clipped drums, short loops, and baile plus phone-speaker compatibility',
 'negative_traits': ['U.S. funk band sound',
                     'smooth lounge mix',
                     'long harmonic progression',
                     'weak bass',
                     'polished pop without baile pressure']}


