STYLE_PRESET = {'id': 'classical_contemporary_art_music',
 'description': {'pt': 'Musica classica e contemporanea de concerto com cores orquestrais, desenvolvimento formal, contraste dinamico, voz ou coro opcional e profundidade acustica.',
                 'en': 'Classical and contemporary art music with orchestral color, formal development, dynamic contrast, optional voice or choir, and acoustic depth.'},
 'style_family': 'classical and contemporary art music',
 'style_prompt': 'Classical and contemporary art music with orchestral color, formal development, '
                 'dynamic contrast, choir or solo voice option, acoustic depth, and expressive '
                 'architectural pacing.',
 'default_language': 'en-US',
 'default_vocal': {'description': 'optional solo, ensemble, or choir vocal delivery with '
                                  'controlled dynamics and clear text setting'},
 'tempo_bpm': 96,
 'key_scale': 'D minor',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['strings',
                     'woodwinds',
                     'brass',
                     'percussion',
                     'piano',
                     'harp',
                     'choir',
                     'electronics'],
 'arrangement': ['notated opening section',
                 'motivic development',
                 'orchestration change',
                 'dynamic contrast',
                 'transformation',
                 'formal cadence'],
 'energy': 'variable',
 'mood': ['formal', 'expressive', 'architectural', 'cinematic', 'timbral'],
 'mix_target': 'wide dynamic range, hall acoustics, stereo depth, and natural orchestral balance',
 'negative_traits': ['pop compression',
                     'fake orchestra blur',
                     'static dynamics',
                     'generic epic scoring',
                     'unsupported tempo claims']}


