STYLE_PRESET = {'id': 'forro_piseiro',
 'description': {'pt': 'Forro e piseiro brasileiro com pulso rapido em 2/4, sanfona ou teclado marcante, zabumba, triangulo, grave eletronico e vocal festivo.',
                 'en': 'Brazilian forro and piseiro with a fast 2/4 pulse, striking accordion or keyboard, zabumba, triangle, electronic low end, and festive vocals.'},
 'style_family': 'Brazilian forro piseiro',
 'style_prompt': 'Brazilian forro and piseiro with fast 2/4 dance pulse, sanfona or keyboard hook, '
                 'zabumba, triangle, compressed electronic low end, bright lead vocal, and playful '
                 'party drive.',
 'default_language': 'pt-BR',
 'default_vocal': {'description': 'direct bright lead vocal with optional rough party tone'},
 'tempo_bpm': 144,
 'key_scale': 'D major',
 'time_signature': 2,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['sanfona',
                     'zabumba',
                     'triangle',
                     'keyboard lead',
                     'electronic kick',
                     'programmed bass',
                     'hand percussion'],
 'arrangement': ['accordion or keyboard hook',
                 'zabumba and triangle groove',
                 'direct vocal verse',
                 'dance chorus',
                 'short loop-based break'],
 'energy': 'high',
 'mood': ['festive', 'northeastern', 'danceable', 'longing', 'playful'],
 'mix_target': 'trio pe-de-serra reference with modern piseiro compression option',
 'negative_traits': ['generic accordion cliche',
                     'missing triangle pulse',
                     'rock-only drums',
                     'overly complex harmony',
                     'slow lounge feel']}


