STYLE_PRESET = {'id': 'french_chanson_auteur_song',
 'description': {'pt': 'Chanson francesa e cancao autoral europeia com vocal proximo e claro, piano ou acordeon, calor de cabare, narrativa e melancolia contida.',
                 'en': 'French chanson and European auteur song with close clear vocals, piano or accordion, cabaret warmth, narrative phrasing, and restrained melancholy.'},
 'style_family': 'French chanson auteur song',
 'style_prompt': 'French chanson and European auteur song with diction-forward close vocal, piano '
                 'or accordion color, cabaret warmth, narrative phrasing, restrained orchestral '
                 'depth, and literary melancholy.',
 'default_language': 'fr-FR',
 'default_vocal': {'description': 'close diction-forward theatrical vocal with speech-song nuance'},
 'tempo_bpm': 82,
 'key_scale': 'A minor',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['piano',
                     'accordion',
                     'acoustic guitar',
                     'double bass',
                     'small drums',
                     'strings',
                     'brass or woodwinds'],
 'arrangement': ['sparse verse',
                 'lyric-led phrasing',
                 'instrumental commentary',
                 'swelling refrain',
                 'final crescendo'],
 'energy': 'low',
 'mood': ['literary', 'intimate', 'ironic', 'theatrical', 'melancholic'],
 'mix_target': 'vocal intelligibility first, cabaret warmth, and restrained orchestral depth',
 'negative_traits': ['hook-first pop repetition',
                     'buried lyrics',
                     'excessive melisma',
                     'club bass',
                     'generic lounge pastiche']}


