STYLE_PRESET = {'id': 'jazz',
 'description': {'pt': 'Jazz com swing ou feel reto, harmonia estendida, secao ritmica conversacional, sopros ou piano, espaco de improviso e dinamica de sala ao vivo.',
                 'en': 'Jazz with swing or straight feel, extended harmony, a conversational rhythm section, horns or piano, improvisational space, and live-room dynamics.'},
 'style_family': 'jazz',
 'style_prompt': 'Jazz with swing or straight feel, extended harmony, conversational rhythm '
                 'section, horn or piano color, optional vocal phrasing, improvisational space, '
                 'and warm live-room dynamics.',
 'default_language': 'en-US',
 'default_vocal': {'description': 'optional jazz lead vocal with behind-the-beat phrasing and '
                                  'light improvisational color'},
 'tempo_bpm': 132,
 'key_scale': 'Bb major',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['saxophone',
                     'trumpet',
                     'piano',
                     'upright bass',
                     'drum kit',
                     'brushes',
                     'guitar',
                     'vibraphone'],
 'arrangement': ['head',
                 'vocal statement',
                 'solo section',
                 'ensemble response',
                 'head return',
                 'tag ending'],
 'energy': 'variable',
 'mood': ['improvised', 'sophisticated', 'conversational', 'warm'],
 'mix_target': 'live-room clarity with natural dynamics, audible interaction, and controlled bleed',
 'negative_traits': ['quantized stiffness',
                     'fake swing',
                     'overcompression',
                     'bland voicings',
                     'static solos']}


