STYLE_PRESET = {'id': 'pop',
 'description': {'pt': 'Pop global com groove 4/4 firme, vocal polido, hook forte, bateria programada, baixo sintetico, camadas harmonicas brilhantes e elevacao emocional.',
                 'en': 'Global pop with a tight 4/4 groove, polished vocals, a strong hook, programmed drums, synth bass, bright harmony layers, and emotional lift.'},
 'style_family': 'global pop',
 'style_prompt': 'Global pop with a tight 4/4 groove, polished lead vocal, strong hook, programmed '
                 'drums, synth bass, bright harmony layers, and radio-ready emotional lift.',
 'default_language': 'en-US',
 'default_vocal': {'description': 'polished close lead vocal with subtle doubles and harmony '
                                  'stacks'},
 'tempo_bpm': 112,
 'key_scale': 'C major',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['lead vocal',
                     'programmed drums',
                     'synth bass',
                     'piano',
                     'guitar',
                     'pads',
                     'vocal chops'],
 'arrangement': ['short intro',
                 'verse',
                 'pre-chorus lift',
                 'big chorus',
                 'post-chorus hook',
                 'bridge or final lift'],
 'energy': 'high',
 'mood': ['catchy', 'direct', 'emotional', 'radio-ready'],
 'mix_target': 'bright vocal-forward mix with clean low end and strong mono compatibility',
 'negative_traits': ['muddy vocals',
                     'long intro',
                     'weak hook',
                     'overcomplex harmony',
                     'dull chorus lift']}


