STYLE_PRESET = {'id': 'reggae',
 'description': {'pt': 'Reggae com groove one-drop, rockers ou steppers, baixo melodico pesado, guitarra skank, organ bubble, metais, espaco dub e vocal caloroso.',
                 'en': 'Reggae with one-drop, rockers, or steppers groove, heavy melodic bass, skank guitar, organ bubble, horns, dub space, and warm vocals.'},
 'style_family': 'reggae',
 'style_prompt': 'Reggae with relaxed one-drop, rockers, or steppers groove, heavy melodic bass, '
                 'offbeat guitar skank, organ bubble, horn responses, dub space, toasting or '
                 'harmony vocals, and warm communal delivery.',
 'default_language': 'en-US',
 'default_vocal': {'description': 'melodic lead vocal with harmony responses, chant feel, or light '
                                  'toasting'},
 'tempo_bpm': 78,
 'key_scale': 'A minor',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['round electric bass',
                     'one-drop drums',
                     'rim clicks',
                     'skank guitar',
                     'organ bubble',
                     'horn lines',
                     'spring reverb',
                     'tape delay'],
 'arrangement': ['cyclic groove',
                 'lead vocal verse',
                 'chorus or chant',
                 'horn response',
                 'dub dropout',
                 'version-style outro'],
 'energy': 'medium',
 'mood': ['spacious', 'warm', 'resistant', 'spiritual', 'communal'],
 'mix_target': 'heavy melodic bass, dry offbeat skank, dub depth, and clear vocal space',
 'negative_traits': ['rushed groove',
                     'weak bass',
                     'stiff skank',
                     'excessive clutter',
                     'shallow dub effects']}


