STYLE_PRESET = {'id': 'rock',
 'description': {'pt': 'Rock guiado por guitarras com backbeat forte, riffs eletricos, baixo presente, vocal melodico, refrao antemico e energia de banda ao vivo.',
                 'en': 'Guitar-driven rock with a strong backbeat, electric riffs, present bass, melodic vocals, an anthemic chorus, and live-band energy.'},
 'style_family': 'guitar rock',
 'style_prompt': 'Guitar-driven rock with a punchy backbeat, electric riffs, bass guitar, melodic '
                 'lead vocal, anthemic chorus, amp texture, and physical band-room energy.',
 'default_language': 'en-US',
 'default_vocal': {'description': 'melodic lead vocal with light rasp and chorus-ready intensity'},
 'tempo_bpm': 124,
 'key_scale': 'E minor',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['electric guitar riffs',
                     'clean jangle or overdrive rhythm guitar',
                     'bass guitar',
                     'drum kit',
                     'lead vocal',
                     'gang vocals',
                     'fuzz, chorus, or delay textures'],
 'arrangement': ['intro riff', 'verse', 'chorus', 'bridge', 'solo or breakdown', 'final chorus'],
 'energy': 'high',
 'mood': ['driving', 'physical', 'rebellious', 'anthemic'],
 'mix_target': 'wide guitars, punchy drums, present bass, and natural amp character',
 'negative_traits': ['synthetic flatness',
                     'weak backbeat',
                     'thin guitars',
                     'buried bass',
                     'over-polished aggression']}


