STYLE_PRESET = {'id': 'schlager_germanic_nordic_pop',
 'description': {'pt': 'Schlager e pop germanico-nordico com pulso 4/4 brilhante, vocal claro, refrao para cantar junto, bateria disco-pop, teclados e polimento sentimental.',
                 'en': 'Schlager and Germanic-Nordic pop with a bright 4/4 pulse, clear vocals, singalong chorus, disco-pop drums, keyboards, and sentimental polish.'},
 'style_family': 'Schlager Germanic Nordic pop',
 'style_prompt': 'Schlager and Germanic-Nordic pop with bright 4/4 pulse, clear lead vocal, '
                 'singalong chorus, disco-pop drums, keyboards, backing choir, and sentimental '
                 'arena polish.',
 'default_language': 'de-DE',
 'default_vocal': {'description': 'clear lead vocal with strong diction and singalong chorus '
                                  'support'},
 'tempo_bpm': 124,
 'key_scale': 'G major',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['programmed drums',
                     'disco-pop kick',
                     'guitars',
                     'keyboards',
                     'accordion',
                     'strings',
                     'brass',
                     'backing choir'],
 'arrangement': ['short intro hook',
                 'verse',
                 'pre-chorus',
                 'chorus',
                 'instrumental break',
                 'final chorus modulation'],
 'energy': 'high',
 'mood': ['sentimental', 'celebratory', 'nostalgic', 'direct'],
 'mix_target': 'polished TV, radio, and arena sound with bright vocal EQ and strong chorus lift',
 'negative_traits': ['complex rhythm',
                     'ambiguous lyrics',
                     'dark underground tone',
                     'weak melody',
                     'buried diction']}


