STYLE_PRESET = {'id': 'uk_bass_music',
 'description': {'pt': 'UK bass music com breaks picotados ou bateria 2-step, sub grave pesado, pads escuros, claps secos, MC opcional e pressao de sound system.',
                 'en': 'UK bass music with chopped breaks or 2-step drums, heavy sub-bass, dark pads, sharp claps, optional MC bars, and sound-system pressure.'},
 'style_family': 'UK bass music',
 'style_prompt': 'UK bass music with chopped breaks or 2-step drums, heavy sub-bass, dark pads, '
                 'sharp claps, optional MC bars, vocal chops, and tense sound-system club '
                 'pressure.',
 'default_language': 'en-GB',
 'default_vocal': {'description': 'optional MC bars, chopped vocals, or sparse club-focused vocal '
                                  'phrases'},
 'tempo_bpm': 140,
 'key_scale': 'F minor',
 'time_signature': 4,
 'duration_seconds': 60,
 'generation_controls': {'instrumental': False},
 'instrumentation': ['chopped breaks',
                     '2-step drums',
                     'sub-bass',
                     'Reese bass',
                     'claps',
                     'vocal chops',
                     'dark pads',
                     'dub delay'],
 'arrangement': ['mixable intro',
                 '16-bar or 32-bar phrase',
                 'breakdown',
                 'drop',
                 'rewind-ready hook',
                 'outro'],
 'energy': 'high',
 'mood': ['urban', 'tense', 'physical', 'nocturnal'],
 'mix_target': 'sound-system low end, sharp drums, controlled sub, and clear MC or vocal space',
 'negative_traits': ['thin bass',
                     'rigid pop drums',
                     'overfull harmony',
                     'weak swing',
                     'soft low-end control']}


